title: Manuel Lämmle
description: Energiefinformatik, Gebäudeenergietechnik
HS Offenburg
manuel.laemmle@hs-offenburg.de
logo: /img/headshot_circle.png
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
